apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fruits-app
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/quarkus-springboot-demo/fruits-app@sha256:6f217b0d236b920ef2e3ad60fe85a2c987fdda086ab01e8fecc83bbe8bdc7750
          imagePullPolicy: Always
          name: user-container
      serviceAccountName: fruits-app-sa
