---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  #storageClassName: iops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgwal-pvc
spec:
  #storageClassName: iops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
