apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  app.kubernetes.io/part-of: argocd

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - cr.yaml
  - user-group.yaml
