---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: fruits-app-ksvc-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fruits-app-ksvc-deploy-run-
        annotations:
          argocd.argoproj.io/hook: PreSync
        labels:
          tekton.dev/pipeline: ksvc-deploy
      spec:
        params:
          - name: GITHUB_REPO_URL
            value: $(params.gitrepositoryurl)
          - name: GITHUB_REPO_REVISION
            value: $(params.gitrevision)
        pipelineRef:
          name: ksvc-deploy
        serviceAccountName: fruits-app-sa
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: quarkus-springboot-demo-sources
          - configMap:
              name: maven-settings
            name: maven-settings
